services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  meilisearch:
    image: getmeili/meilisearch:v1.6
    ports:
      - "7700:7700"
    env_file:
      - .env
    volumes:
      - ./data/meili:/meili_data
