-- courses registry and resource tagging

CREATE TABLE courses (
    id      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name    TEXT NOT NULL UNIQUE,
    aliases TEXT[] NOT NULL DEFAULT '{}'
);

ALTER TABLE resources ADD COLUMN course_id UUID REFERENCES courses(id);
CREATE INDEX idx_resources_course_id ON resources(course_id);

-- seed courses from courses.json
-- note: alias collisions exist:
--   DSA -> "Digital Signal Analysis" AND "Data Structures and Algorithms"
--   ISS -> "Introduction to Spatial Sciences" AND "Introduction to Software Systems"

INSERT INTO courses (name, aliases) VALUES
    ('Language Typology and Universals', ARRAY['LTU']),
    ('Digital Signal Analysis', ARRAY['DSA']),
    ('Language and Society', ARRAY['LNS']),
    ('Computational Linguistics 2', ARRAY['CL2']),
    ('Statistical Mechanics', ARRAY['SM']),
    ('Thermodynamics', ARRAY['TH']),
    ('Science Lab 2', ARRAY['SL2']),
    ('Quantum Mechanics', ARRAY['QM']),
    ('Probability and Random Processes', ARRAY['PRP']),
    ('Electrodynamics', ARRAY['EDY']),
    ('Organic Chemistry', ARRAY['OC']),
    ('Intro to Biology', ARRAY['ITB']),
    ('Statistical Thermodynamics', ARRAY['STT']),
    ('Biomolecular Structure', ARRAY['BMSTR']),
    ('Computer Networks', ARRAY['CN']),
    ('Machine Data Learning', ARRAY['MDL']),
    ('Embedded Systems Workshop', ARRAY['ESW']),
    ('Algorithm Analysis and Design', ARRAY['AAD']),
    ('Automate Theory', ARRAY['AT']),
    ('Design and Analysis of Software Systems', ARRAY['DASS']),
    ('Introduction to Human Sciences', ARRAY['IHS']),
    ('Science 2', ARRAY['SCI2']),
    ('Probability and Statistics', ARRAY['PRS']),
    ('Data and Applications', ARRAY['DNA']),
    ('Mathemetics-2I', ARRAY['MAT3']),
    ('Operating Systems and Networks', ARRAY['OSN']),
    ('Science 1', ARRAY['SCI1']),
    ('Introduction to Algorithms Engineering(H2)', ARRAY['IAE']),
    ('Introduction to Information Security(H1)', ARRAY['2S']),
    ('Computer Graphics(H1)', ARRAY['CG']),
    ('Introduction to Quantum Information and Computation (H1)', ARRAY['IQIC']),
    ('Introduction to Coding Theory (H2)', ARRAY['ICT']),
    ('Performance Modeling of Computer Systems (H1)', ARRAY['PMCS']),
    ('Introduction to Spatial Science and Technology (H1)', ARRAY['ISSAT', 'ISST']),
    ('Basic Electronic Circuits', ARRAY['BEC']),
    ('Research Methods in the Human Sciences', ARRAY['RMHS']),
    ('Computational Linguistics 1', ARRAY['CL1']),
    ('Introduction to Linguistics 1', ARRAY['ITL1']),
    ('Introduction to Linguistics 2', ARRAY['ITL2']),
    ('Computing in Sciences - 1', ARRAY['CIS1']),
    ('Computing in Sciences - 2', ARRAY['CIS2']),
    ('General and Structural Chemistry', ARRAY['GSC']),
    ('Classical Mechanics', ARRAY['CM']),
    ('Spatial Thinking and Practice', ARRAY['STP']),
    ('Introduction to Spatial Sciences', ARRAY['ISS']),
    ('Digital Systems and Microcontrollers', ARRAY['DSM']),
    ('Data Structures and Algorithms', ARRAY['DSA']),
    ('Introduction to Software Systems', ARRAY['ISS']),
    ('Linear Algebra', ARRAY['LA']),
    ('Discrete Structures', ARRAY['DISC', 'DS']),
    ('Real Analysis', ARRAY['RA']),
    ('Computer Systems Organisation', ARRAY['CSO']),
    ('Computer Programming', ARRAY['CPRO', 'C Programming']),
    ('Networks, Signals and Systems', ARRAY['NSS', 'NESS']),
    ('Analog Electronic Circuits', ARRAY['AEC']),
    ('Information and Communication', ARRAY['IC']),
    ('Electrical Science', ARRAY['ES']),
    ('Thinking and Knowing in the Human Sciences - I', ARRAY['TKHS1']),
    ('Making of the Contemporary India', ARRAY['MOCI']),
    ('Making of Contemporary World', ARRAY['MOCW']),
    ('Modern Complexity Theory', ARRAY['MCT']),
    ('Advanced NLP', ARRAY['ANLP']),
    ('Computer Vision', ARRAY['CV']),
    ('Statistical Methods in AI', ARRAY['SMAI']),
    ('Information Retrieval and Extraction', ARRAY['IRE']),
    ('Software Engineering', ARRAY['SE']),
    ('Compilers', ARRAY['CMP']),
    ('Distributed Systems', ARRAY['DS']),
    ('Advanced Computer Networks', ARRAY['ACN']),
    ('Database Systems', ARRAY['DBS']),
    ('Open Quantum Systems and Quantum Thermodynamics', ARRAY['OQS']),
    ('Universe Across Scales', ARRAY['UAS']),
    ('Dynamical Processes in Complex Networks', ARRAY['DPCN']),
    ('Differential Equations', ARRAY['DE']),
    ('Biomolecular Structure Interaction and Dynamics', ARRAY['BMSID']),
    ('Selected Topics in Instrumental Analysis', ARRAY['STIA']),
    ('Advanced Mathematical Structures', ARRAY['AMS']),
    ('Topics in NanoSciences', ARRAY['TNS']),
    ('Mathematical Models in Biology', ARRAY['MMB']),
    ('Probablistic Graphical Models', ARRAY['PGM']),
    ('Chemistry Topics for Engineers', ARRAY['CTE']),
    ('Molecular Modeling and Simulations', ARRAY['MMS']),
    ('Spatial Informatics', ARRAY['SI']),
    ('Desing for Social Innovation', ARRAY['DSI']),
    ('Research in Information Security', ARRAY['RIS']),
    ('Digital Image Processing', ARRAY['DIP']),
    ('Linguistic Data-2', ARRAY['LD2']),
    ('Technology Product Entrepreneurship', ARRAY['TPE']),
    ('Topics in Reinforcement Learning', ARRAY['TRL']),
    ('Speech Technology', ARRAY['SPT']),
    ('Environmental Science', ARRAY['EVS']),
    ('Intro to Neural and Cognitive Modelling', ARRAY['INCM']),
    ('Data Analytics 1', ARRAY['DA1']),
    ('Natural Language Processing Applications', ARRAY['NLA']),
    ('Spatial Data Sciences', ARRAY['SDS']),
    ('Quantum Information Theory', ARRAY['QIT']),
    ('Introduction to Game Theory', ARRAY['IGT']),
    ('Natural Language Processing', ARRAY['NLP']),
    ('Principles of Information Security', ARRAY['POIS']),
    ('Complexity and Advanced Algorithms', ARRAY['CAA']),
    ('Principles of Programming Languages', ARRAY['POPL']),
    ('Disaster Management', ARRAY['DM']),
    ('Remote Sensing', ARRAY['RS']),
    ('Hydroinformatics', ARRAY['HYD']),
    ('AI and Human Rights', ARRAY['AIHR']),
    ('Work, Entrepreneurship and Technology in Contemporary Societies', ARRAY['WETCS']),
    ('Introduction to Economics', ARRAY['ECO']),
    ('Introduction to Shakespeare', ARRAY['SHK']),
    ('Theories and Practices of Nationalism', ARRAY['TPN']),
    ('Environmental and Social Governance in Mineral Extraction', ARRAY['ESGME']),
    ('Introduction to History', ARRAY['HIS']),
    ('Ethics in Research', ARRAY['ERS']),
    ('Introduction to Film Studies', ARRAY['IFS']),
    ('Introduction to Philosophy of Technology', ARRAY['IPT']),
    ('Science Technology and Society', ARRAY['STS']),
    ('Growth and Development', ARRAY['GND']),
    ('Rethinking Corruption in India', ARRAY['RCI']),
    ('Environment and Politics in India', ARRAY['EPI']),
    ('Introduction to Sociology', ARRAY['SOC']),
    ('Technology and Social Movements', ARRAY['TSM']),
    ('Introduction to Psychology', ARRAY['PSY']),
    ('Readings from Hindi Literature', ARRAY['RHL']),
    ('Migrants and Migrations in Modern South Asia', ARRAY['MMSA']),
    ('Sociology of Platform Economies', ARRAY['SPE']),
    ('Introduction to Literature', ARRAY['LIT']),
    ('Gender, Culture and Representation', ARRAY['GCR']),
    ('Basics of Ethics', ARRAY['BOE']),
    ('Linguistics 1', ARRAY['LIN1']),
    ('Bioinformatics', ARRAY['BI']),
    ('Spectroscopy', ARRAY['SPEC']),
    ('Chemical Kinetics and Reaction Dynamics', ARRAY['CKRD']),
    ('Applied Ethics', ARRAY['AE']);
